### ISSUE TITLE
Config files are missing rope_adjustments

### ISSUE THREAD

**Issue by mtasic85** [Lightning-AI/litgpt#1777]
In config yaml files, section `model_config:` is missing `rope_adjustments:`.

```yaml
model_name: "Llama-3.2-1B"

model_config:
  rope_adjustments:
    factor: 32.0
    low_freq_factor: 1.0
    high_freq_factor: 4.0
    original_max_seq_len: 8192
```

`rope_adjustments` is not recognized.
